var mongoose=require('mongoose');

var accountsectionSchema=new mongoose.Schema({
  _id                 :Number,
  revenueallocation   :Number,
  developmentallocation:Number,
  ownallocation        :Number,
  foreignsource        :Number,
  rrevenueallocation:Number,
  revenueallocationexpense:Number,
  percentageofrevenueallocation:String,
  rdevelopmentallocation :Number,
  developmentallocationexpense :Number,
  percentageofdevelopmentallocation:String,
  rownallocation                   :Number,
  ownallocationexpense             :Number,
  percentageofownallocation        :String,
  rforeignsource                   :Number,
  foreignsourceexpense             :Number,
  percentageofforeignsource        :String,
  rothersourceallocation           :Number,
  othersource                      :Number,
  percentageofother                :String,
  insolvencygrant                  :Number,
  ownincome                        :Number,
  specialdevelopmentallocation     :Number,
  otherallocation                  :Number,
  educationexpense                 :Number,
  percentageofeducationbudget      :String,
  researchexpense                  :Number,
  percentageofresearchbudget       :String,
  salaryexpense                    :Number,
  percentageofsalarybudget         :String,
  researchschoolarshipexpense      :Number,
  percentageofresearchschoolarshipbudget:String,
  transportationexpense            :Number,
  percentageoftransportationbudget :String,
  electricityexpense               :Number,
  percentageofelectricitybudget    :String,
  infrastructuralexpense           :Number,
  percentageofinfrastructuralbudget:String,
  otherexpense                     :Number,
  percentageofotherbudget          :String,
  medicationexpense                :Number,
  percentageofmedication           :String,
  administrasionexpense            :Number,
  percentageofadministrasionexpense:String,
  pensonexpense                    :Number,
  percentageofpensonexpense        :String,
  residentialadvantagemaleteacher  :Number,
  residentialadvantagefemaleteacher:Number,
  residentialadvantagemaleofficer  :Number,
  residentialadvantagefemaleofficer:Number,
  residentialadvantagemalethirdclassemploye:Number,
  residentialadvantagefemalethirdclassemploye:Number,
  residentialadvantagemalefourthclassemploye :Number,
  residentialadvantagefemalefourthclassemploye:Number
});

module.exports=accountsectionuser=mongoose.model('accountsection',accountsectionSchema);
