var mongoose=require('mongoose');
// define the schema for our user model
var Schema=new mongoose.Schema({
  _id                 :Number,
  csetotalbscstudent  :Number,
  csemalebscstudent   :Number,
  csefemalebscstudent :Number,
  csetotalmscstudent  :Number,
  csemalemscstudent   :Number,
  csefemalemscstudent :Number,
  csetotalmfilstudent :Number,
  csemalemfilstudent  :Number,
  csefemalemfilstudent:Number,
  csetotalphdstudent  :Number,
  csemalephdstudent   :Number,
  csefemalephdstudent :Number,
  cseforeignmalebscstudent   :Number,
  cseforeignfemalebscstudent :Number,
  cseforeignmalemscstudent   :Number,
  cseforeignfemalemscstudent :Number,
  cseforeignmalemfilstudent  :Number,
  cseforeignfemalemfilstudent:Number,
  cseforeignmalephdstudent   :Number,
  cseforeignfemalephdstudent :Number,
  csefulltimemfilmaleteacher  :Number,
  csefulltimemfilfemaleteacher:Number,
  cseparttimemfilmaleteacher  :Number,
  cseparttimemfilfemaleteacher:Number,
  csefulltimephdmaleteacher   :Number,
  csefulltimephdfemaleteacher :Number,
  cseparttimephdmaleteacher   :Number,
  cseparttimephdfemaleteacher :Number,
  csefulltimemscmaleteacher   :Number,
  csefulltimemscfemaleteacher :Number,
  cseparttimemscmaleteacher   :Number,
  cseparttimemscfemaleteacher :Number,
  csefulltimebscmaleteacher   :Number,
  csefulltimebsefemaleteacher :Number,
  cseparttimebscmaleteacher   :Number,
  cseparttimebscfemaleteacher :Number,
  csefulltimeothermaleteacher :Number,
  csefulltimeotherfemaleteacher:Number,
  cseparttimeothermaleteacher  :Number,
  cseparttimeotherfemaleteacher:Number,
  cseresearch1  :Number,
  cseresearch2  :Number,
  cseresearch3  :Number,
  cseresearch4  :Number,
  cseresearch5  :Number,
  cseresearch6  :Number,
  csejournal    :Number,
  cseconference :Number,
  cseresearch8  :Number,
  cseresearch9  :Number,
  cseresearch10 :Number
});

var user=mongoose.model('cse',Schema);

module.exports=user=mongoose.model('cse',Schema);