var mongoose=require('mongoose');

var educationsectionSchema=new mongoose.Schema({
  _id                 :Number,
  cseforeignbscmalestudent:Number,
  cseforeignbsctfemalestudent:Number,
  gender1                    :String,
  faculty1                   :String,
  department1                :String,
  degree1                    :String,
  foreignstudentcountry1     :String,
  foreignschoolarshipbscstudent1:String,
  foreignownexpensebscstudent1:String,
  gender2                    :String,
  faculty2                   :String,
  department2                :String,
  degree2                    :String,
  foreignstudentcountry2     :String,
  foreignschoolarshipbscstudent2:String,
  foreignownexpensebscstudent2:String,
  gender3                    :String,
  faculty3                   :String,
  department3                :String,
  degree3                    :String,
  foreignstudentcountry3     :String,
  foreignschoolarshipbscstudent3:String,
  foreignownexpensebscstudent3:String,
  gender4                    :String,
  faculty4                   :String,
  department4                :String,
  degree4                    :String,
  foreignstudentcountry4     :String,
  foreignschoolarshipbscstudent4:String,
  foreignownexpensebscstudent4:String,
  gender5                    :String,
  faculty5                   :String,
  department5                :String,
  degree5                    :String,
  foreignstudentcountry5     :String,
  foreignschoolarshipbscstudent5:String,
  foreignownexpensebscstudent5:String,
  gender6                    :String,
  faculty6                   :String,
  department6                :String,
  degree6                    :String,
  foreignstudentcountry6     :String,
  foreignschoolarshipbscstudent6:String,
  foreignownexpensebscstudent6:String,
  gender7                    :String,
  faculty7                   :String,
  department7                :String,
  degree7                    :String,
  foreignstudentcountry7     :String,
  foreignschoolarshipbscstudent7:String,
  foreignownexpensebscstudent7:String,
  dropoutfaculty1             :String,
  dropoutdepartment1          :String,
  dropoutmalestudent1         :String,
  dropoutfemalestudent1       :String,
  dropoutfaculty2             :String,
  dropoutdepartment2          :String,
  dropoutmalestudent2         :String,
  dropoutfemalestudent2       :String,
  dropoutfaculty3             :String,
  dropoutdepartment3          :String,
  dropoutmalestudent3         :String,
  dropoutfemalestudent3       :String,
  dropoutfaculty4             :String,
  dropoutdepartment4          :String,
  dropoutmalestudent4         :String,
  dropoutfemalestudent4       :String,
  dropoutfaculty5             :String,
  dropoutdepartment5          :String,
  dropoutmalestudent5         :String,
  dropoutfemalestudent5       :String,
  fullfreemalestudent         :Number,
  fullfreefemalestudent       :Number,
  schoolarshipandfeloshipmalestudent:Number,
  schoolarshipandfeloshipfemalestudent:Number,
  schoolarshipmalestudent     :Number,
  schoolarshipfemalestudent   :Number,
  feloshipmalestudent         :Number,
  feloshipfemalestudent       :Number,
  otherschoolarshipmalestudent:Number,
  otherschoolarshipfemalestudent:Number,
  bscpasssession              :Number,
  bscadmitmalestudent         :Number,
  bscadmitfemalestudent       :Number,
  bscpassmalestudent          :Number,
  bscpassfemalestudent        :Number,
  percentageofbscpass         :String,
  mscpasssession              :Number,
  mscadmitmalestudent         :Number,
  mscadmitfemalestudent       :Number,
  mscpassmalestudent          :Number,
  mscpassfemalestudent        :Number,
  percentageofmscpass         :String,
  mfilpasssession             :Number,
  mfiladmitmalestudent        :Number,
  mfiladmitfemalestudent      :Number,
  mfilpassmalestudent         :Number,
  mfilpassfemalestudent       :Number,
  percentageofmfilpass        :String,
  phdpasssession              :Number,
  phdadmitmalestudent         :Number,
  phdadmitfemalestudent       :Number,
  phdpassmalestudent          :Number,
  phdpassfemalestudent        :Number,
  percentageofphdpass         :String
});

module.exports=educationsectionuser=mongoose.model('educationsection',educationsectionSchema);