var mongoose=require('mongoose');

var foundationsectionSchema=new mongoose.Schema({
  _id                 :Number,
  totalprofessorapproveseat:Number,
  approvemaleprofessor     :Number,
  approvefemaleprofessor   :Number,
  parttimemaleprofessor    :Number,
  parttimefemaleprofessor  :Number,
  totalmaleprofessor       :Number,
  totalfemaleprofessor     :Number,
  totalassociateprofessorapproveseat:Number,
  approvemaleassociateprofessor     :Number,
  approvefemaleassociateprofessor   :Number,
  parttimemaleassociateprofessor    :Number,
  parttimefemaleassociateprofessor  :Number,
  totalmaleassociateprofessor       :Number,
  totalfemaleassociateprofessor     :Number,
  totalassistantprofessorapproveseat:Number,
  approvemaleassistantprofessor     :Number,
  approvefemaleassistantprofessor   :Number,
  parttimemaleassistantprofessor    :Number,
  parttimefemaleassistantprofessor  :Number,
  totalmaleassistantprofessor       :Number,
  totalfemaleassistantprofessor     :Number,
  totallecturarapproveseat          :Number,
  approvemalelecturar               :Number,
  approvefemalelecturar             :Number,
  parttimemalelecturar              :Number,
  parttimefemalelecturar            :Number,
  totalmalelecturar                 :Number,
  totalfemalelecturar               :Number,
  totalteachingassistantapproveseat :Number,
  approvemaleteachingassistant      :Number,
  approvefemaleteachingassistant    :Number,
  parttimemaleteachingassistant     :Number,
  parttimefemaleteachingassistant   :Number,
  totalmaleteachingassistant        :Number,
  totalfemaleteachingassistant      :Number,
  totalvisitingprofessorapproveseat :Number,
  approvemalevisitingprofessor      :Number,
  approvefemalevisitingprofessor    :Number,
  parttimemalevisitingprofessor     :Number,
  parttimefemalevisitingprofessor   :Number,
  totalmalevisitingprofessor        :Number,
  totalfemalevisitingprofessor      :Number,
  totalhonoraryprofessorapproveseat :Number,
  approvemalehonoraryprofessor      :Number,
  approvefemalehonoraryprofessor    :Number,
  parttimemalehonoraryprofessor     :Number,
  parttimefemalehonoraryprofessor   :Number,
  totalmalehonoraryprofessor        :Number,
  totalfemalehonoraryprofessor      :Number,
  totalsupernumararyprofessorapproveseat:Number,
  approvemalesupernumararyprofessor :Number,
  approvefemalesupernumararyprofessor:Number,
  parttimemalesupernumararyprofessor:Number,
  parttimefemalesupernumararyprofessor:Number,
  totalmalesupernumararyprofessor    :Number,
  totalfemalesupernumararyprofessor  :Number,
  totalemeritusprofessorapproveseat  :Number,
  approvemaleemeritusprofessor       :Number,
  approvefemaleemeritusprofessor     :Number,
  parttimemaleemeritusprofessor      :Number,
  parttimefemaleemeritusprofessor    :Number,
  totalmaleemeritusprofessor         :Number,
  totalfemaleemeritusprofessor       :Number,
  totalnationalprofessorapproveseat  :Number,
  approvemalenationalprofessor       :Number,
  approvefemalenationalprofessor     :Number,
  parttimemalenationalprofessor      :Number,
  parttimefemalenationalprofessor    :Number,
  totalmalenationalprofessor         :Number,
  totalfemalenationalprofessor       :Number,
  workingmaleteacher                 :Number,
  workingfemaleteacher               :Number,
  absentmaleteacher                  :Number,
  absentfemaleteacher                :Number,
  maleeducationvacationteacher       :Number,
  femaleeducationvacationteacher     :Number,
  maletransmissionteacher            :Number,
  femaletransmissionteacher          :Number,
  maleliyenteacher                   :Number,
  femaleliyenteacher                 :Number,
  malefreesalaryteacher              :Number,
  femalefreesalaryteacher            :Number,
  maleunapproveteacher               :Number,
  femaleunapproveteacher             :Number,
  maleparttimeteacher                :Number,
  femaleparttimeteacher              :Number,
  totalpermanentofficerapproveseat   :Number,
  permanentmaleofficer               :Number,
  permanentfemaleofficer             :Number,
  totalcontactualofficerapproveseat  :Number,
  contactualmaleofficer              :Number,
  contactualfemaleofficer            :Number,
  totalthirdclasspermanentemployeapproveseat:Number,
  thirdclasspermanentmaleemploye     :Number,
  thirdclasspermanentfemaleemploye   :Number,
  totalfourthclasspermanentemployeapproveseat:Number,
  fourthclasspermanentmaleemploye    :Number,
  fourthclasspermanentfemaleemploye  :Number,
  totaladhokemployeapproveseat       :Number,
  adhokmaleeemploye                  :Number,
  adhokfemaleeemploye                :Number,
  totaldailypresentemployeapproveseat:Number,
  dailypresentmaleeemploye           :Number,
  dailypresentfemaleeemploye         :Number

});

module.exports=foundationsectionuser=mongoose.model('foundationsection',foundationsectionSchema);